ALTER TABLE dbo.[NBA Stats 2024]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2023]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2022]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2021]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2020]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2019]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2018]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2017]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA Stats 2016]
ADD CHAMP BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.[NBA 24 25 Team Stats]
ADD CHAMP BIT NOT NULL DEFAULT 0