SELECT Team, GP, W, L, ROUND(Win, 2) AS 'WIN%', ROUND(Min, 2) AS MIN, ROUND(Pts, 2) AS PTS, ROUND(FGM, 2) AS FGM, ROUND(FGA, 2) AS FGA, ROUND(FG, 2) AS 'FG%', 
ROUND(_3PM, 2) AS '3PM', ROUND(_3PA, 2) AS '3PA', ROUND(_3P, 2) AS '3P%', ROUND(FTM, 2) AS FTM, ROUND(FTA, 2) AS FTA, ROUND(FT, 2) AS 'FT%', 
ROUND(OREB, 2) AS OREB, ROUND(DREB, 2) AS DREB, ROUND(OREB, 2) AS 'REB(Total)', ROUND(AST, 2) AS AST, ROUND(TOV, 2) AS TOV, ROUND(STL, 2) AS STL, 
ROUND(BLK, 2) AS BLK, ROUND(BLK_Against, 2) AS 'BLK(Against)', ROUND(PF, 2) AS PF, ROUND(PF, 2) AS 'PF(Drawn)', YR, CHAMP, ROUND(New_Champ,2) AS 'NEWCHAMP' FROM dbo.[Predicted 2026 NBA champ]
WHERE YR = '2026' 
ORDER BY NEWCHAMP DESC